# Generated by Django 4.2.5 on 2023-10-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soilapp', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
    ]
